### ISSUE TITLE
Changed API for safe settings

### ISSUE THREAD

**Issue by gimaldi** [Gage-Technologies/mistral-go#1]
Hello,
Mistral's API param `safe_mode` is changed. The new name is `safe_prompt`.
In your file `chat.go` simply rename the key name of `requestData` maps in `MistralClient` methods `Chat` and `ChatStream`, from `safe_mode` to `safe_prompt`.

Ciao

**Comment by sam-ulrich1** [comment]
Thanks for this! Fixing now. I'm pushing on them to give me this info ahead of time so the client doesn't break

**Comment by sam-ulrich1** [comment]
Completed

**Comment by sam-ulrich1** [comment]
@gimaldi fixed in v0.1.3

**Comment by gimaldi** [comment]
I confirm that the problem is solved.
Thanks for your efforts.
