### ISSUE TITLE
Failed after updating the mistral AI API

### ISSUE THREAD

**Issue by oleksiikhrypko** [Gage-Technologies/mistral-go#3]
After updating the mistral AI API, I got the following error :

(HTTP Error 422)
{"object":"error","message":{"detail":[{"type":"extra_forbidden","loc":["body","messages",0,"user","name"],"msg":"Extra inputs are not permitted","input":"","url":"https://errors.pydantic.dev/2.6/v/extra_forbidden"},{"type":"extra_forbidden","loc":["body","messages",0,"user","tool_calls"],"msg":"Extra inputs are not permitted","input":null,"url":"https://errors.pydantic.dev/2.6/v/extra_forbidden"}]},"type":"invalid_request_error","param":null,"code":null}

**Comment by oleksiikhrypko** [comment]
fix: https://github.com/Gage-Technologies/mistral-go/pull/2

**Comment by sam-ulrich1** [comment]
Fixed on v1.0.1

Sorry for the delay. GitHub never notified me of this. I'll review my notification settings.
